version: '3'
services:
  app:
    image: uberchuckie/observium
    container_name: observium
    environment:
      - TZ=Europe/Prague
    volumes:
      - observium-config:/config
      - observium-logs:/opt/observium/logs
      - observium-rrd:/opt/observium/rrd
    ports:
      - "8889:8668"
    restart: unless-stopped

volumes:
      observium-config:
      observium-logs:
      observium-rrd:


